### ISSUE TITLE
Issue 1 - Load Random Image

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/anime-unrelated#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view an example image on the page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can navigate to the URL and will be greeted with a random image overlayed with a random quote

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/125551036-d8993a07-e2a7-4b7e-8cd9-e264920d50f2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML Skeleton with Head items and Links
- [x] link the necessary fonts api
- [x] Create header area with title and icon
- [x] Create the main area with Canvas
- [x] Add CSS styling to header and main
- [x] Add JS for load of the canvas area and text
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
![image](https://user-images.githubusercontent.com/75236087/126424913-7ce2e7ca-a61a-4dc9-8f85-a62350d7a713.png)
