### ISSUE TITLE
Issue 6 - Feature: User can use the app on mobile

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/anime-unrelated#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can randomize on mobile sized screens and see an image sized for their screen

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While on a mobile-sized screen, clicking the randomize button will change the size of the canvas to the correct size for the screen

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/133383007-97b81d66-bac2-4d9b-90cb-7617c56e4dff.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add checks in JS to change the layout based on mobile sizing (below the width of the image)
- [x] Add custom screen size checks
- [x] Adjust the click function to change canvas size based on the screen size at the time
- [x] Adjust width and height attributes to reduce based on sizing
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
Success: 
![image](https://user-images.githubusercontent.com/75236087/174426109-e7e1746f-0d92-48f7-b098-863dfe03c1de.png)

**Comment by easton-morris** [comment]
![Mobile](https://user-images.githubusercontent.com/75236087/174553519-907f0f6e-c71d-4969-93f7-5d8172666408.gif)
