### ISSUE TITLE
Issue 2 - User can randomize the image

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/anime-unrelated#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can randomize the image and quote combo

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click the "Randomize" button and a new image background will load with a new quote on it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/126426200-344622dd-4e77-4f70-83be-bc0b7f123b95.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create Randomize button in HTML and style it with CSS
- [x] Create functions for updating the quoteText and image src attribute
- [x] Create XHR Requests to start pulling info off of the APIs
- [x] Create function for resetting the img src to the pulled image
- [x] Create function for resetting the quote and attribution text and setting it to the pulled info
- [x] Create a listener to run the randomize img, randomize text, img load and text load functions on button click 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
![issue2exp](https://user-images.githubusercontent.com/75236087/126737475-fe435292-63d2-47e8-9876-29bc25d28c00.gif)
