### ISSUE TITLE
Issue 3 -  User can select anime

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/anime-unrelated#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select and anime from the drop down

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the drop down and click on one of the anime displayed alphabetically

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/133185100-2b2771eb-2d51-4076-b032-ef046f1770ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a form area
- [x] Create a drop down select element with a search option
- [x] Create a new function to run if anything but "random" is selected in the drop down
- [x] Adjust the randomize button click function to account for the check on the drop down
- [x] Adjust the anime specific quote pull functions to enable pagination if available
- [x] Adjust the anime specific quote pull functions to account for undefined's in the random integer
- [x] Change the text size if the quote is too long
- [x] Style the drop down with CSS
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on desktop screens.
  - [x] Create GIFs of the feature being used for inclusion in Pull Request.

**Comment by easton-morris** [comment]
![image](https://user-images.githubusercontent.com/75236087/130396820-cf798bee-9d2d-4014-89c4-32ce81b75e2a.png)

Need to reduce the text size if quote is too long. [FIXED]

**Comment by easton-morris** [comment]
![issue3example](https://user-images.githubusercontent.com/75236087/133190454-2b8c1eae-baa3-424b-b1cf-1b3b0df4338d.gif)
