### ISSUE TITLE
Issue 4 - Feature: User can keep the image

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/anime-unrelated#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can keep the image but randomize the quote

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a toggle button to keep the image on next randomization

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the button in HTML and create the appropriate custom data attributes
- [x] Position and style the button using CSS
- [x] Give the buttons a data attribute for toggle
- [x] Create a function to style the button accordingly on click and update the custom data attributes
- [x] Create functions to pass the data into the json file for localstorage
- [x] adjust the randomize functions to include a logic gate based on the current value of the of the toggle
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
![ToggleButtons](https://user-images.githubusercontent.com/75236087/174251859-17834161-9339-4eb1-a457-ce1ab3ca85b5.gif)
