### ISSUE TITLE
Issue 5 - Feature: User can keep the quote 

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/anime-unrelated#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can toggle to keep the quote but change the image

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click a toggle button so that when randomized, only the image will change

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a button
- [x] Assign it toggle design attributes and status data attr
- [x] Change the randomize image function to not run if the toggle for the image is on
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
![Uploading ToggleButtons.gif…]()
